platform :ios, '12.0'

target 'SwiftRingNode_Example' do
  use_frameworks!
  
  # Pods for SwiftRingNode_Example
  pod 'SwiftRingNode', :path => '../'

  target 'SwiftRingNode_Tests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
